### PR TITLE
fixed: https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/59

### PR DESCRIPTION
**Pull request by ganeshrvel**
This fixed the issue https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/59 but I am not sure if this is the right approach or not.

Suggestions are welcome.

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Sendo PR to Branch **bugfix**

I am going to do some tests and analyze what this command does.

**Comment by ganeshrvel** [comment]
@RodrigoSMarques done

**Comment by RodrigoSMarques** [comment]
@ganeshrvel 
I did the tests and it really works.
I will run a few more tests to ensure that there will be no conflict with FlutterActivity, as the method will be called twice at startup.

**Comment by ganeshrvel** [comment]
Great! Please keep me posted as we are also using the the same set of changes

**Comment by RodrigoSMarques** [comment]
@ganeshrvel 
The change causes conflict when using FlutterActivity.
I am finalizing a project and I will have time to review this implementation in the coming weeks.

**Comment by RodrigoSMarques** [comment]
The PR was not accepted.
If changes are applied, projects that use FlutterActivity will stop working. The change cannot be used in both cases.
I did tests and realized that sometimes FlutterFragmentActivity may not work, because BranchSDK also needs the Activity Lifecycle (onActivityStarted) and it is not called.

**Pull request closed without merging**
