### PR TITLE
Exposed setRequestMetadata method

### PR DESCRIPTION
**Pull request by ganeshrvel**

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Sendo PR to Branch **enhancement**.

Is this working?
I read in the documentation that this command must be called before the InitSession and this way it will not work.

**Comment by ganeshrvel** [comment]
> I read in the documentation that this command must be called before the InitSession and this way it will not work.

Won't this work?

```dart
FlutterBranchSdk.setRequestMetadata(
  requestMetadataKey,
  requestMetadataValue,
);

_branchStreamSubscription = FlutterBranchSdk.initSession().listen((data) {
  .....
  .....
}, onError: (error) {
  final platformException = error as PlatformException;

  log.error(error);

});

```

**Comment by RodrigoSMarques** [comment]
I'm not sure.
The initSession in Flutter receives through Stream the result of the initSession of the native code that was called at App launch.

From what I read in the documentation, this command should be called in native before initSession.

**Comment by ganeshrvel** [comment]
Seems like it is working.

**Comment by RodrigoSMarques** [comment]
@ganeshrvel 
Submit the PR to Branch **enhancement** and update the documentation.

**Pull request closed without merging**
