### PR TITLE
enableDebugMode replaced

### PR DESCRIPTION
**Pull request by smedic**
/FlutterBranchSDK( 5343): Branch SDK in DebugMode
I/BranchSDK( 5343): enableDebugMode is deprecated and all functionality has been disabled. If you wish to enable logging, please invoke enableLogging. If you wish to simulate installs, please see add a Test Device (https://help.branch.io/using-branch/docs/adding-test-devices) then reset your test device's data (https://help.branch.io/using-branch/docs/adding-test-devices#section-resetting-your-test-device-data). If you wish to use the test key rather than the live key, please invoke enableTestMode.

**enableDebugMode** deprecated; therefore, enableTestMode and enableLogging are added to solve Branch method deprecation.

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Hi @smedic .
Thanks for the PR, but these changes are already ready in the "enhancement" branch for Android and iOS, a few days ago.

I didn't generate a new release, because I have to update the documentation and I didn't have time.
I will do it later this week.

About Branch.enableTestMode. I will leave the configuration in AndroidManifest, as stated in the documentation:

```java
    /**
     * <p>
     * Enables the test mode for the SDK. This will use the Branch Test Keys. This is same as setting
     * "io.branch.sdk.TestMode" to "True" in Manifest file.
```

**Comment by smedic** [comment]
Okay, great. I haven't seen a branch with fixes, sorry.
I ll close this 👍

**Comment by RodrigoSMarques** [comment]
> Okay, great. I haven't seen a branch with fixes, sorry.
> I ll close this 👍

Hi @smedic 
Without any problems. By the end of the week, I will make the release available.

**Comment by jliu-branch** [comment]
hello @RodrigoSMarques ,

can we use 'enableTestMode' now? seems it is not on Flutter documentation 

thanks

**Comment by RodrigoSMarques** [comment]
@jliu-branch 
In Android update key ** io.branch.sdk.TestMode** to true in AndroidManifest.xml

```xml
<application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:supportsRtl="true"
        android:name=".MyApplication">

  <meta-data android:name="io.branch.sdk.TestMode" android:value="false" /> <!-- Set to true to use Branch_Test_Key -->
  <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_my_live_key" />
  <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_my_test_key" />
</application>
```
In iOS, update file INFO.PLIST in key "branch_key" with "key_test_my_test_key"

**Comment by jliu-branch** [comment]
@RodrigoSMarques thanks

can we do something like 
'Branch.enableTestMode'  with the native SDK?

**Pull request closed without merging**
