### PR TITLE
Feature/web support

### PR DESCRIPTION
**Pull request by mathatan**
Web support via branch js sdk. Not all functionality is directly available and some differences are a bit cryptic due to lacklustre documentation on branches behalf.

Currently unsupported api:

- validateSDKIntegration (somewhat unable to do..?)
- listOnSearch (doesn't look like there's any support for this on JS sdk)
- removeFromSearch (doesn't look like there's any support for this on JS sdk)
- setIOSSKAdNetworkMaxTime (not sure if this is relevant)
- isUserIdentified (likely the implementation is incorrect)
- setRequestMetadata (haven't implemented the data addition to requests)

Supported functionality:

- getLatestReferringParams
- getFirstReferringParams
- showShareSheet (partial support)
- registerView (the actual implementation might not be the correct one)
- loadRewards
- redeemRewards
- getCreditHistory
- setIdentity
- logout
- disableTracking
- initSession (changed to require branchKey for web tho - options would be to include that in index.html, but for now it's in dart code)
- getShortUrl (some meta-data functionality might not work)
- trackContent
- trackContentWithoutBuo

Larger refactors include move of flutter_sdk to flutter_sdk_native and abstract stub for both web SDK and native SDK to implement.

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Hi @mathatan 
Thanks for the contribution.

I will analyze your PR.
The implementation for Web is different from the one I was designing (scheduled to start at the end of the month) which is following the pattern of Federated Plugins and using the Branch REST API.
[https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins)

I will create a specific branch, it should not be merged into the master.

There is already a 2.0.0 version available for null-safety, so I have to take it easy.

**Comment by mathatan** [comment]
I think I originally was planning on doing it as a federated plugin, but decided against it due to it requiring larger changes in the plugin file structure and I wanted to be able to merge any changes that was made in the master before this was merged and/or completed.

The actual implementation shouldn't be that different even with federated plugins though. I think it's mainly about configuration, file structure and how pubspec is setup. 

We had the need to support web asap, so I decided to do this now and make it available as is.

Feel free to modify and use it as you see fit. If you'd prefer I can make a pull request to another branch just let me know. I wasn't really expecting this to be accepted to master as is. (not sure if I can change the target for this one anymore or if you can change it)

**Comment by RodrigoSMarques** [comment]
Hi @mathatan 
I analyzed your code and ran tests. It was very good.

I will implement these changes in the version of the Plugin that is in Pre-release: 2.0.0

During the month of February I will do this.

Thank you for your contribution

**Comment by RodrigoSMarques** [comment]
Hi @mathatan ,
Thank you very much for your contribution.

I am closing this PR, as it will not be merged into the repository.
I implemented Flutter's guidelines for multi-platform packages.
I used your code entirely to call the javascript functions.
I created the web-support branch and the example app is running here:
https://flutter-branch-sdk.netlify.app
I'm doing some more tests, updating the documentation and in the next few days I will release the new version.

**Pull request closed without merging**
