### PR TITLE
Migrate web implementation to js_interop

### PR DESCRIPTION
**Pull request by hnvn**
- Migrate `branch_js.dart` and `flutter_branch_sdk_web.dart` to `dart:js_interop`
- Refactor `index.html` in `example/web` to use new template
- This PR would address the issue #361

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Thanks for the contribution. I will analyze it.

**Comment by hnvn** [comment]
Hi @RodrigoSMarques , please have a look at this PR when you are available. Thank you in advance

**Comment by RodrigoSMarques** [comment]
@hnvn 
Performing tests, I identified that the QR Code generation function is not working.
Can you check?
I will release the release after adjusting this.

**Comment by hnvn** [comment]
Yeah, please guide me how to test it

**Pull request merged**
