### PR TITLE
Fix crash when adding a boolean control param

### PR DESCRIPTION
**Pull request by quetool**
I am using `ios_nativelink` as boolean, [as probably it is supposed to be used](https://help.branch.io/using-branch/docs/creating-a-deep-link#deep-linking) and it is working great on iOS but it is crashing on Android with the following `java.lang.Boolean cannot be cast to java.lang.String`

```
_Exception (Exception: PlatformException(error, java.lang.Boolean cannot be cast to java.lang.String, null, java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
  at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkHelper.convertToLinkProperties(FlutterBranchSdkHelper.java:165)
  at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.showShareSheet(FlutterBranchSdkPlugin.java:383)
  at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onMethodCall(FlutterBranchSdkPlugin.java:241)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
  at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:255)
  at android.app.ActivityThread.main(ActivityThread.java:8224)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

So I changed `Map.Entry<String, String> content` to `Map.Entry<String, Object> content` for `controlParams` as for `customMetadata`

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Thanks for the contribution.

**Comment by quetool** [comment]
Thanks to you for this great package @RodrigoSMarques !
It's been a while I don't open a PR on Github, is it ok your project is forked automatically into my account?
Also, if PR is ok, do you have an estimated date to merge it?
Thanks!

**Comment by RodrigoSMarques** [comment]
> Thanks to you for this great package @RodrigoSMarques !
> It's been a while I don't open a PR on Github, is it ok your project is forked automatically into my account?
> Also, if PR is ok, do you have an estimated date to merge it?
> Thanks!

I don't have a date for the merge yet as there are other changes in the works.

Before accepting your PR, I have a question to check first.

The `addControlParameter` method only accepts string values in the native layer (swift, java, javascript).

On iOS although there was no error, values other than string were ignored.

So the correct thing would be to change it in Dart, to accept only string.

I'm contacting branch support to validate.

**Comment by RodrigoSMarques** [comment]
@quetool 

Send the value as a string ("true") and not as a boolean (true).

The native SDK only accepts string values.

I'm preparing a fix where the value will be converted to string when sending to the SDK, but later I will release a new version, changing the data type in the method signature.

**Comment by quetool** [comment]
It's weird cause I was sending the value as Boolean on iOS. Thanks anyway, I will use String. 

Then we can close this PR?

**Comment by RodrigoSMarques** [comment]
> It's weird cause I was sending the value as Boolean on iOS. Thanks anyway, I will use String.
> 
> Then we can close this PR?

Yes, but on iOS, although the crash did not occur, when checking the link properties, the value was not being configured.

Any non-string value was being ignored.

You can close it, until the weekend I will be making the new version available with automatic conversion from value to string.

**Comment by RodrigoSMarques** [comment]
Fix completed - Version 6.3.0.

**Pull request closed without merging**
