### PR TITLE
Bug Fix: Fix iOS Facebook Login & add support for Facebook Deep Linking + improve attribution for Apple Search Ads

### PR DESCRIPTION
**Pull request by Morkos**
Hi @RodrigoSMarques ,

Copied below from previous PR:

Correct, it does not work with the Facebook Login. Facebook tries to call the URL scheme fb[appId]://authorize after login but branch does not handle this URL scheme correctly so the app does not get opened. I added a fix for this on Line 65 in SwiftFlutterBranchSdkPlugin.swift.

I added two other features as well.

To allow deeplinks from Facebook to work appropriately [1] and improve attribution for people using branch links on Apple Search Ads [2].

[1]: https://help.branch.io/using-branch/docs/facebook-app-install-ads (see registerFacebookDeepLinkingClass method)
[2]: https://help.branch.io/developers-hub/docs/ios-advanced-features#section-track-apple-search-ads

Best,
Mark

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Hi @Morkos 

I tried to reproduce the Facebook Login problem and I couldn't.
I have an app with Branch (flutter_branch_sdk 0.2.0) and Facebook Login (flutter_facebook_login 3.0.0). With the Facebook app installed or without an app, the user data authentication and recovery process was successfully performed.
I need more details, for example a video or code snippet to try to reproduce the problem.

About the command ```dart Branch.getInstance.()RegisterFacebookDeepLinkingClass ```.

I will study and think of a solution. I would not like to depend on the Facebook SDK. Not everyone uses this feature and this would include unnecessary code in the IPA. Maybe put the code directly in the base project's Swift code, just like google maps.

**Comment by Morkos** [comment]
Hi @RodrigoSMarques,

Just to be sure, I'm referring to iOS devices, not Android. Android works fine, but was having issues with iOS (my iOS is 13+).

Best,
Mark

**Comment by RodrigoSMarques** [comment]
Hi @Morkos 
Yes. IOS devices. I did not mention Android devices. I tested on a physical device (13.3) and on the simulator (13.3). Facebook Login worked correctly.

My configs in INFO.PLIST
Captura de Tela 2020-02-27 às 20 13 39

Processing:
IMG_9104
IMG_9105
IMG_9106
IMG_9107

**Comment by amondnet** [comment]
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution#swift-2
```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    // Pass the url to the handle deep link call
    let branchHandled = Branch.getInstance().application(
        application,
        open: url,
        options: options
    )
    if (!branchHandled) {
        // If not handled by Branch, do other deep link routing for the
        // Facebook SDK, Pinterest SDK, etc
    }
    return branchHandled
}

func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    let handledByBranch = Branch.getInstance().continue(userActivity)
    return handledByBranch
}
```

**Comment by RodrigoSMarques** [comment]
Hi @amondnet 
I have identified this difference and have already corrected the code.
The Branch documentation has changed and I am updating the links in the documentation to release the new version of the plugin.
This will be done until the end of the week.

**Comment by RodrigoSMarques** [comment]
Hi @Morkos 
Please test version 0.3.0 and check if the problem with Facebook Login persists.
In this version:
- Added improve attribution for Apple Search Ads.

About Facebook, I suggest that this change be made directly in the native code, adding the code before the line:
```swift
GeneratedPluginRegistrant.register (with: self)
```

**Comment by RodrigoSMarques** [comment]
Closed. No activity in the last 15 days.

**Pull request closed without merging**
